if(ESP_PLATFORM)
    idf_component_register(SRCS "pca9685.c" INCLUDE_DIRS "include")
else()
    cmake_minimum_required(VERSION 3.16)
    project(ainekio_pca9685 C)
    add_library(ainekio_pca9685 STATIC pca9685.c)
    target_include_directories(ainekio_pca9685 PUBLIC include)
    target_compile_features(ainekio_pca9685 PUBLIC c_std_11)
    target_compile_options(ainekio_pca9685 PRIVATE -Wall -Wextra -Werror -Wpedantic)
    add_executable(test_pca9685 tests/test_pca9685.c)
    target_link_libraries(test_pca9685 PRIVATE ainekio_pca9685)
    target_compile_options(test_pca9685 PRIVATE -Wall -Wextra -Werror -Wpedantic)
    enable_testing()
    add_test(NAME pca9685 COMMAND test_pca9685)
endif()
