"""Publish the completed offline comparison as a reviewable local artifact."""
from pathlib import Path
import json,hashlib,html,math,shutil
import numpy as np
ROOT=Path('/home/greggles/Ainekio');TMP=Path('/tmp/ainekio-compact-linkage');OUT=ROOT/'docs/gait-research/compact-linkage-20261005'
OUT.mkdir(exist_ok=True)
rows=json.loads((TMP/'verified.json').read_text());clearance=json.loads((TMP/'clearance.json').read_text());screen=json.loads((TMP/'screen.json').read_text());poses=np.load(TMP/'poses.npz');base=rows[0];by={(r['crank'],r['pickup']):r for r in rows}
assert len(clearance)==4
for f in ['screen.py','verify.py','clearance.py','report.py','native_check.py','verified.json','screen.json','clearance.json','native_all_gaits.json','mesh-reference.npz','mesh-reference.json','collision-poses.npz']:
 shutil.copyfile(TMP/f,OUT/f)
inputs=['geometry.json','motion.c','walk_kinematics.c','clip.c','servo_profile.json','motions/run/config.json','motions/locomotion/config.json','motions/locomotion/crab.json','motions/locomotion/contact-hulls.json','motions/gestures/catalog.json']
manifest={str(Path('Slave/software/models/v2-12servo')/p):hashlib.sha256((ROOT/'Slave/software/models/v2-12servo'/p).read_bytes()).hexdigest() for p in inputs}
for p in (ROOT/'Slave/software/models/v2-12servo/motions/gestures').glob('*/manifest.json'):manifest[str(p.relative_to(ROOT))]=hashlib.sha256(p.read_bytes()).hexdigest()
result=dict(source_commit='13fc3e46009f9b0cbb0b5c1c63af8cc659e415c6',fixed_mm=dict(carrier=40,rod=38,distal=55),servo_mounts_changed=False,candidates=len(screen),reachable_candidates=sum(r['valid'] for r in screen),poses=len(poses['q']),gait_poses=int(poses['gait_count']),clip_poses=len(poses['q'])-int(poses['gait_count']),groups=poses['names'].tolist(),recommended=dict(crank=28,pickup=30,rod=38,carrier=40,distal=55),geometry_changes_applied=False,source_sha256=manifest,assumptions=['Mass 0.512 kg; equal vertical support among flagged grounded feet.','Quasistatic massless rigid links; no impact, inertia, flex, friction or measured motor curve.','Neutral standing: zero model joints, level body, four feet, vertical force only.','Gait torque: worst of Fx/Fz = -0.2 and +0.2, CAD sole contact point.','Conditional torque-speed score = abs(torque)/1.8 kgf cm + abs(speed)/600 deg/s at the same sample and joint.','Run200 native preparation, steady motion and finish at 1 ms and 0.25 ms; sample rate variation is disclosed in verified.json.','Other gaits and named motion interpolation sampled at 120 Hz.','Geometric reach means sampled knee and lower-leg poses preserved. This is not all conceivable manual poses or hardware pulse qualification.','Mesh interference uses 1349 representative poses and original styled surface vertex extensions; no hardware fasteners, wires, foot/body collisions, clearance-distance or containment proof.','Original crank/carrier-servo mesh intersections exist in folded poses; candidate checks compare with that baseline.'],sources=['https://towerpro.com.tw/product/mg90s-3/','https://modernrobotics.northwestern.edu/nu-gm-book-resource/velocity-kinematics-and-statics/'])
(OUT/'summary.json').write_text(json.dumps(result,indent=2))
p=json.loads((ROOT/'Slave/software/models/v2-12servo/geometry.json').read_text())['parameters'];C=np.array(p['C_new']);O=np.array(p['O']);D=np.array(p['D_neutral']);beta=p['beta_neutral']
svg=['<svg xmlns="http://www.w3.org/2000/svg" width="1040" height="330" viewBox="0 0 1040 330"><rect width="1040" height="330" fill="#f4f7fa"/><style>text{font-family:Arial,sans-serif;fill:#172637;font-size:14px}.title{font-size:19px;font-weight:bold}</style>']
for col,(r,b,title) in enumerate([(24,24,'Original 24 / 24'),(28,30,'Compact 28 / 30'),(32,36,'Long 32 / 36')]):
 E=D+b*np.array([math.cos(beta),math.sin(beta)]);v=E-C;d=np.linalg.norm(v);t=math.atan2(v[1],v[0])-math.acos((r*r+d*d-38**2)/(2*r*d));P=C+r*np.array([math.cos(t),math.sin(t)])
 def pt(x):return (col*345+40+x[0]*3.8,305-(x[1]-40)*3.8)
 svg.append(f'<text x="{col*345+30}" y="30" class="title">{title}</text>')
 for a,z,c,w in [(C,O,'#8092a4',3),(O,D,'#66788a',9),(C,P,'#dc6436',8),(P,E,'#629086',6),(D,E,'#306ed1',8)]:
  ax,ay=pt(a);zx,zy=pt(z);svg.append(f'<line x1="{ax}" y1="{ay}" x2="{zx}" y2="{zy}" stroke="{c}" stroke-width="{w}" stroke-linecap="round"/>')
 for a in [C,O,D,E,P]:
  x,y=pt(a);svg.append(f'<circle cx="{x}" cy="{y}" r="4" fill="#fff" stroke="#172637" stroke-width="1.5"/>')
 svg.append(f'<text x="{col*345+30}" y="320">Same mounts and knee position; 38 mm rod</text>')
svg.append('</svg>');(OUT/'comparison.svg').write_text(''.join(svg))
table=[]
for r,b in [(24,24),(26,28),(28,30),(28,31),(30,34),(32,36)]:
 z=by[r,b];stand=z['standing_vertical_four_feet_kgcm'][1];red=100*(1-stand/base['standing_vertical_four_feet_kgcm'][1]);run=z['run200_1ms_025ms'][1];runred=100*(1-run['score']/base['run200_1ms_025ms'][1]['score'])
 table.append(f'<tr><td>{r} / {b}</td><td>{stand:.3f}</td><td>{red:.1f}%</td><td>{runred:.1f}%</td><td>{run["peak_speed_deg_s"][2]:.0f}</td><td>{z["min_circle_margin_mm"]:.3f}</td></tr>')
contacts=''.join(f'<li>{z["crank"]}/{z["pickup"]}: {len(z["new_contacts_vs_original"])} new surface-contact samples versus original; {sum(z["contact_counts"].values())} total recorded contact samples.</li>' for z in clearance)
doc='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Compact linkage comparison</title><style>body{max-width:1080px;margin:35px auto;padding:0 20px;font:16px/1.55 system-ui;color:#172637}h1{line-height:1.2}table{border-collapse:collapse;width:100%;font-size:14px}th,td{text-align:left;padding:10px;border-bottom:1px solid #ccd4de}th{background:#eef2f6}img{width:100%}.note{background:#eef3fa;padding:15px;border-left:4px solid #306ed1}a{color:#235dc2}code{font-size:13px}</style>
<h1>Shorter arms, existing reach and servo mounts</h1>
<p><b>Recommended compact compromise: 28 mm crank and 30 mm pickup.</b> Keep the 40 mm carrier, 38 mm rod and 55 mm lower leg. This halves the extensions added to the original 24/24 mm arms: +4/+6 mm instead of +8/+12 mm. It does not reproduce all of the long design's leverage improvement.</p>
<img src="comparison.svg" alt="Planar joint-center diagrams comparing original, compact and long arms with fixed mounts, carrier and rod"><p>Joint-center schematic in the neutral pose, at the same scale. Orange: crank; blue: pickup; green: connecting rod; gray: carrier. The foot-side geometry stays unchanged.</p>
<table><tr><th>Crank / pickup mm</th><th>Standing carrier kgf·cm</th><th>Standing load reduction</th><th>Run200 combined demand reduction</th><th>Run peak crank °/s</th><th>Minimum circle reach margin mm</th></tr>'''+''.join(table)+'''</table>
<p>Percentages compare with original 24/24/38 geometry under identical assumptions. Standing figures are four-foot, level-body vertical-load estimates at 512 g. Combined demand is a conditional simultaneous torque-and-speed score, not measured force capacity. The minimum circle margin is distance from a linkage reach boundary, not clearance between solid parts.</p>
<p>26/28 mm is a smaller alternative, retaining about 11% standing load reduction. 28/31 mm improves standing leverage more than 28/30, but its Upright reach margin is only 0.375 mm versus 1.056 mm; it is a less tolerant geometric choice. Neither choice adds a software motion restriction.</p>
<h2>Motion preservation and verification</h2>
<p>Screened 169 integer-mm combinations (crank 20–32 mm, pickup 24–36 mm) at fixed 38 mm rod. Forty preserve the sampled assembly branch and all sampled poses. The set contains 87,027 native poses: 56,033 locomotion poses and 30,994 clip poses, covering Walk, Run, Crawl, Crab, both turning directions, crab sidesteps, and all 23 named motions. Preparation, speed changes and finish are included. Arbitrary manual joint combinations are not exhaustively tested.</p>
<p>The superficially appealing 24/27 and 28/32 pairs fail the existing Upright motion: maximum reach deficits 0.657 mm and 0.251 mm. They are not proposed as full-repertoire replacements.</p>
<p>Independent finite-difference force calculations agree within 9.6×10⁻¹¹ Nm. Sampled material-point positions match the original mechanism within 10⁻⁶ mm. Candidate Run200 solutions also agree with separately compiled native firmware motion code within 0.00072°. These checks prove the numerical retargeting, not physical servo performance.</p>
<h2>Part envelopes</h2><p>Compared the original styled crank, carrier, pickup, rod, two servo meshes and housing across 1,349 representative and extreme poses from all 41 command groups. This is a surface-intersection comparison using extended source meshes, not a final manufactured-part clearance qualification.</p><ul>'''+contacts+'''</ul>
<p>Some folded poses already intersect the carrier-servo mesh in the original model. Fasteners, wires, adjacent legs and body/foot collisions are outside this scoped comparison.</p>
<h2>Limits of the load estimate</h2>
<p>The model uses massless rigid links and equal weight sharing among marked supporting feet; friction, acceleration, impact, flex and actual servo torque-speed behavior are not measured. The Run calculation includes horizontal contact force up to 20% of vertical force. Its screening reference is 1.8 kgf·cm and 600°/s from <a href="https://towerpro.com.tw/product/mg90s-3/">TowerPro's MG90S specification</a>; the installed servos are not thereby qualified. Force mapping follows <a href="https://modernrobotics.northwestern.edu/nu-gm-book-resource/velocity-kinematics-and-statics/">the Jacobian/virtual-work relation</a>.</p>
<p class="note">All compared designs still exceed the assumed servo envelope at the full requested Run timing. These dimensions improve leverage and packaging; they do not establish that this 512 g robot will stand up or run successfully on its current servos.</p>
<h2>Scope and reproduction</h2>
<p>This task changes no Blender geometry, calibration, firmware or runtime limits. The live Blender model remains the previously applied 32/36 mm design. A chosen replacement requires CAD edits and motion/calibration retargeting before installation.</p>
<p>Evidence: <a href="summary.json">assumptions and source hashes</a>, <a href="verified.json">verified candidate metrics</a>, <a href="screen.json">all 169 candidates</a>, <a href="clearance.json">surface-intersection checks</a>. Offline scripts are <a href="screen.py">screen.py</a>, <a href="verify.py">verify.py</a> and <a href="clearance.py">clearance.py</a>.</p>
<p>Scripts currently use this workspace and /tmp/ainekio-compact-linkage paths. Build native samplers with <code>cmake -S Slave/software/models/v2-12servo -B /tmp/ainekio-compact-linkage/native -DCMAKE_BUILD_TYPE=Release</code>, then build targets <code>v2_walk_command v2_clip_sample</code>. Run screen.py and verify.py with NumPy. Run clearance.py in background Blender with the captured mesh-reference and collision-poses arrays in /tmp. Run200 verification reuses the prior run200-torque-speed-20261005 analyzer and the retained Downloads/Ainekio-Run200-Linkage-Study snapshot. No script connects to the robot.</p></html>'''
doc=doc.replace('<h2>Part envelopes</h2>','<p>A separately compiled 28/30 mm native sampler also completes all 18 locomotion command groups with unchanged timing, agreeing with the retargeted joint trajectories within 0.00070°. See <a href="native_all_gaits.json">native gait results</a> and <a href="native_check.py">native_check.py</a>.</p><h2>Part envelopes</h2>')
doc=doc.replace('with the captured mesh-reference and collision-poses arrays in /tmp.','after copying the included mesh-reference.npz and collision-poses.npz arrays into /tmp/ainekio-compact-linkage. Run native_check.py to compile and compare the compact native gait sampler.')
(OUT/'report.html').write_text(doc)
print(OUT/'report.html')
