#!/usr/bin/env python3
"""Install the existing gateway-owned AP/hostapd/DHCP service contract on Ubuntu.

Run once as root. Installation neither starts the hotspot nor changes the uplink.
The running gateway owns hotspot start/stop, including the Body Control toggle.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import pwd
import re
import shutil
import stat
import subprocess
import tempfile


MARKER = "# Generated by Master/install-robot-hotspot.py\n"
UNITS = (
    "ainekio-hotspot-interface.service",
    "ainekio-hotspot.service",
    "ainekio-hotspot-dhcp.service",
)


def read_credentials(path: Path) -> tuple[str, str]:
    """Import only SSID and WPA credentials, never executable host configuration."""
    metadata = path.stat()
    if not stat.S_ISREG(metadata.st_mode) or metadata.st_mode & 0o077:
        raise ValueError("Hotspot credential file must be a regular owner-only file (mode 0600).")
    fields: dict[str, str] = {}
    for line in path.read_text().splitlines():
        key, separator, value = line.partition("=")
        if separator and key in ("ssid", "wpa_passphrase", "wpa_psk"):
            if key in fields:
                raise ValueError(f"Duplicate hotspot credential field: {key}")
            fields[key] = value
    ssid = fields.get("ssid", "")
    if not 1 <= len(ssid.encode()) <= 32 or "\x00" in ssid:
        raise ValueError("Hotspot SSID must contain 1 to 32 UTF-8 bytes.")
    if ("wpa_passphrase" in fields) == ("wpa_psk" in fields):
        raise ValueError("Supply exactly one WPA passphrase or pre-shared key.")
    if "wpa_passphrase" in fields:
        password = fields["wpa_passphrase"]
        if not 8 <= len(password) <= 63 or any(not 32 <= ord(c) <= 126 for c in password):
            raise ValueError("WPA passphrase must contain 8 to 63 printable ASCII characters.")
        credential = "wpa_passphrase=" + password
    else:
        if not re.fullmatch(r"[0-9a-fA-F]{64}", fields["wpa_psk"]):
            raise ValueError("WPA pre-shared key must contain exactly 64 hexadecimal digits.")
        credential = "wpa_psk=" + fields["wpa_psk"]
    return ssid, credential


def render_configuration(interface: str, operator: str, mac: str,
                         ssid: str, credential: str, channel: int) -> dict[str, tuple[str, int]]:
    if not re.fullmatch(r"[a-zA-Z0-9_-]{1,15}", interface) or interface == "aineap0":
        raise ValueError("Select an existing uplink interface distinct from aineap0.")
    if not re.fullmatch(r"(?:[0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2}", mac):
        raise ValueError("The uplink must have a six-byte MAC address.")
    if channel not in range(1, 12):
        raise ValueError("Select a permitted 2.4 GHz channel from 1 to 11.")
    octets = bytearray.fromhex(mac.replace(":", ""))
    octets[0] = (octets[0] | 2) & 0xfe
    octets[-1] ^= 0x80
    ap_mac = ":".join(f"{value:02x}" for value in octets)
    device_unit = interface.replace("-", "\\x2d")
    return {
        "etc/ainekio-network/hostapd.conf": (MARKER + f"""interface=aineap0
driver=nl80211
ssid={ssid}
hw_mode=g
channel={channel}
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
{credential}
ctrl_interface=/run/ainekio-hotspot/hostapd
""", 0o600),
        "etc/ainekio-network/dnsmasq.conf": (MARKER + """interface=aineap0
bind-dynamic
port=0
dhcp-range=10.42.77.20,10.42.77.200,255.255.255.0,12h
dhcp-option=option:router
dhcp-option=option:dns-server
dhcp-authoritative
dhcp-leasefile=/run/ainekio-hotspot-dhcp/dnsmasq.leases
""", 0o600),
        "etc/NetworkManager/conf.d/80-ainekio-hotspot.conf": (MARKER + """[device-ainekio-hotspot]
match-device=interface-name:aineap0
managed=0
""", 0o644),
        "etc/systemd/network/10-ainekio-hotspot.link": (MARKER + """[Match]
OriginalName=aineap0

[Link]
NamePolicy=
Name=aineap0
MACAddressPolicy=none
""", 0o644),
        "etc/systemd/system/ainekio-hotspot-interface.service": (MARKER + f"""[Unit]
Description=Ainekio private robot Wi-Fi interface
BindsTo=sys-subsystem-net-devices-{device_unit}.device
Wants=NetworkManager.service
After=sys-subsystem-net-devices-{device_unit}.device NetworkManager.service

[Service]
Type=oneshot
ExecStart=/usr/sbin/iw dev {interface} interface add aineap0 type __ap addr {ap_mac}
ExecStartPost=/usr/sbin/ip address add 10.42.77.1/24 dev aineap0
ExecStartPost=/usr/sbin/ip link set aineap0 up
ExecStopPost=-/usr/sbin/iw dev aineap0 del
RemainAfterExit=yes
""", 0o644),
        "etc/systemd/system/ainekio-hotspot.service": (MARKER + """[Unit]
Description=Ainekio private robot Wi-Fi hotspot
Requires=ainekio-hotspot-interface.service
After=ainekio-hotspot-interface.service
PartOf=ainekio-hotspot-interface.service

[Service]
Type=simple
RuntimeDirectory=ainekio-hotspot
RuntimeDirectoryMode=0750
ExecStart=/usr/sbin/hostapd /etc/ainekio-network/hostapd.conf
Restart=on-failure
RestartSec=5
""", 0o644),
        "etc/systemd/system/ainekio-hotspot-dhcp.service": (MARKER + """[Unit]
Description=Address assignment for Ainekio private robot Wi-Fi
Requires=ainekio-hotspot-interface.service ainekio-hotspot.service
After=ainekio-hotspot-interface.service ainekio-hotspot.service
PartOf=ainekio-hotspot-interface.service

[Service]
Type=simple
RuntimeDirectory=ainekio-hotspot-dhcp
RuntimeDirectoryMode=0750
RuntimeDirectoryPreserve=restart
ExecStartPre=/usr/bin/chown dnsmasq /run/ainekio-hotspot-dhcp
ExecStartPre=/usr/sbin/dnsmasq --test --conf-file=/etc/ainekio-network/dnsmasq.conf
ExecStart=/usr/sbin/dnsmasq --keep-in-foreground --conf-file=/etc/ainekio-network/dnsmasq.conf --pid-file= --user=dnsmasq
Restart=on-failure
RestartSec=5
""", 0o644),
        "etc/polkit-1/rules.d/49-ainekio-hotspot.rules": ("// Generated by Master/install-robot-hotspot.py\n" + f"""polkit.addRule(function(action, subject) {{
    if (action.id === "org.freedesktop.systemd1.manage-units" &&
        subject.user === {json.dumps(operator)} &&
        {json.dumps(list(UNITS))}.indexOf(action.lookup("unit")) !== -1 &&
        ["start", "stop"].indexOf(action.lookup("verb")) !== -1) {{
        return polkit.Result.YES;
    }}
}});
""", 0o644),
    }


def install_files(root: Path, files: dict[str, tuple[str, int]]) -> None:
    # Validate every existing owner before changing any file.
    for relative, (content, _) in files.items():
        destination = root / relative
        marker = content.splitlines(keepends=True)[0]
        if destination.is_symlink() or (destination.exists() and
                not destination.read_text().startswith(marker)):
            raise ValueError(f"Existing unmanaged configuration preserved: {destination}")
    for relative, (content, mode) in files.items():
        destination = root / relative
        destination.parent.mkdir(parents=True, exist_ok=True,
                                 mode=0o700 if relative.startswith("etc/ainekio-network/") else 0o755)
        with tempfile.NamedTemporaryFile(mode="w", dir=destination.parent, delete=False) as handle:
            temporary = Path(handle.name)
            handle.write(content)
        try:
            temporary.chmod(mode)
            temporary.replace(destination)
        finally:
            temporary.unlink(missing_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--interface", required=True, help="Station/uplink interface, e.g. wlan0")
    parser.add_argument("--operator", required=True, help="Local account that runs the gateway")
    parser.add_argument("--credentials", required=True, type=Path, help="Owner-only hostapd file supplying SSID and WPA credentials")
    parser.add_argument("--channel", type=int, default=1)
    args = parser.parse_args()
    try:
        if os.geteuid() != 0:
            raise ValueError("Run this installer as root; it installs system services.")
        pwd.getpwnam(args.operator)
        pwd.getpwnam("dnsmasq")
        missing = [name for name in ("hostapd", "dnsmasq", "iw", "ip", "nmcli", "systemctl", "systemd-analyze", "udevadm")
                   if not shutil.which(name)]
        if missing:
            raise ValueError("Missing hotspot dependencies: " + ", ".join(missing) +
                             "; install hostapd dnsmasq-base iw iproute2 network-manager polkitd.")
        for unit in UNITS:
            if subprocess.run(["systemctl", "is-active", "--quiet", unit], check=False).returncode == 0:
                raise ValueError("Stop the gateway/hotspot before updating its installed configuration.")
        ssid, credential = read_credentials(args.credentials)
        mac = (Path("/sys/class/net") / args.interface / "address").read_text().strip()
        files = render_configuration(args.interface, args.operator, mac, ssid, credential, args.channel)
        with tempfile.TemporaryDirectory() as directory:
            paths = []
            for relative, (content, _) in files.items():
                if relative.endswith(".service"):
                    path = Path(directory) / Path(relative).name
                    path.write_text(content)
                    paths.append(str(path))
            subprocess.run(["systemd-analyze", "verify", *paths], check=True)
        install_files(Path("/"), files)
        subprocess.run(["udevadm", "control", "--reload"], check=True)
        subprocess.run(["systemctl", "daemon-reload"], check=True)
        subprocess.run(["nmcli", "general", "reload", "conf"], check=True)
    except (OSError, KeyError, ValueError, subprocess.CalledProcessError) as exc:
        parser.exit(1, f"Hotspot installation failed: {exc}\n")
    print("Installed the gateway-owned robot hotspot services; none were started or boot-enabled.")
    print("Set AINEKIO_HOTSPOT=1 in .env, then restart Master/start-physical-gateway.sh.")
    print("Robot LAN endpoint: ws://10.42.77.1:8790/robot (existing gateway pairing is still required).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
