import json,hashlib,importlib.util
from pathlib import Path
P=Path(__file__).resolve().parent
index=json.loads((P/'motion-index.json').read_text());blender=json.loads((P/'blender-review-summary.json').read_text())
spec=importlib.util.spec_from_file_location('timing',P/'timing.py');timing=importlib.util.module_from_spec(spec);spec.loader.exec_module(timing)
reviews=[];timings=[]
for m in index['commands']:
 f=P/'commands'/m['command'];s=json.loads((f/'source-review.json').read_text());v=json.loads((f/'interpolation-validation.json').read_text());assert s['passed'],m['command']
 c=json.loads((f/'execution-contract.json').read_text());schedule=timing.build_schedule(c);full=timing.build_schedule(c,include_demo_recovery=True)
 assert abs(schedule['duration_s']-c['completion']['semantic_end_s'])<1e-6
 assert abs(full['duration_s']-m['duration_s'])<1e-6
 end=timing.locate(schedule,1e6);assert end['complete'] and end['source_rate']==0
 half=timing.build_schedule(c,scale=2);assert abs(half['duration_s']*2-schedule['duration_s'])<1e-6
 timings.append(dict(command=m['command'],command_duration_s=schedule['duration_s'],with_optional_recovery_s=full['duration_s'],completion_source_time_s=end['source_time_s'],final_rate_zero=True,scale_two_checked=True))
 reviews.append(dict(command=m['command'],source=s,interpolation=v))
 text=(f/'README.md').read_text().split('\n## Integrated Blender and handoff\n')[0]
 text+=f'\n## Integrated Blender and handoff\n\nSaved library: `Ainekio-Motion-Library.blend`, frames **{m["start_frame"]}–{m["end_frame"]}** at 24 fps. [Preview](preview.mp4). The library selector is `select_motion("{m["command"]}", play=True)`.\n\n`source.csv`, `schema.json`, `manifest.json` and `execution-contract.json` are the independent firmware research handoff. Positions are mm and actuator angles are geometric radians; electrical calibration is not supplied. Run `python3 export_command.py` after regeneration. `timing.py` shares one clock across all joints and excludes optional demonstration recovery by default; add `--include-demo-recovery` to inspect that path. Operating timing remains unset.\n\nThe reviewed source and saved poses are reported in `source-review.json`, `interpolation-validation.json`, and `blender-validation.json`. Visor and inter-part collision checks are deferred at the owner’s request.\n'
 (f/'README.md').write_text(text)
summary=dict(commands=reviews,blender_poses_reviewed=sum(r['sampled_poses'] for r in blender),maximum_evaluated_joint_connection_error_mm=max(r['maximum_joint_disconnection_mm'] for r in blender),maximum_evaluated_foot_prediction_error_mm=max(r['maximum_foot_prediction_error_mm'] for r in blender),minimum_evaluated_sole_z_mm=min(r['minimum_evaluated_sole_z_mm'] for r in blender),collision_checked=False,hardware_qualified=False)
(P/'review-summary.json').write_text(json.dumps(summary,indent=2)+'\n');(P/'timing-review.json').write_text(json.dumps(timings,indent=2)+'\n')
cross=dict(reviewed_by='Three command agents cross-reviewed another group; root reviewed numeric sources, exports and saved Blender geometry.',passed_commands=[m['command'] for m in index['commands']],material_findings=[dict(command='celebrate',finding='Converter diagonals comment contradicted mirrored original numeric targets.',resolution='Corrected V2 to alternating rear pair CAD FL/FR and front pair RL/RR; regenerated, re-exported and updated Blender.',status='resolved'),dict(command='all',finding='New phase section labels were not recognized by shared timing helper.',resolution='Restored clip section; explicit execution_role excludes optional demonstration recovery by default. All schedules tested.',status='resolved'),dict(command='displays',finding='Repeated inherited face visibility guards exceeded Blender expression length.',resolution='Compacted equivalent Boolean expressions and verified earlier visibility; all live drivers valid.',status='resolved')],deferred=['Visor and inter-part collisions per owner instruction','Physical mass balance, servo stops, contact strength/friction and electrical qualification'])
(P/'cross-review.json').write_text(json.dumps(cross,indent=2)+'\n')
lines=['# Motion-library validation','','All twelve command sources passed the independent source review and gesture cross-review. The saved Blender mechanism was evaluated at **'+str(summary['blender_poses_reviewed'])+' poses**, including subframes.','','| Command | Demo seconds | Min assumed margin mm | Peak speed deg/s | Peak acceleration deg/s² |','| --- | ---: | ---: | ---: | ---: |']
for m,r in zip(index['commands'],reviews):lines.append(f'| {m["command"]} | {m["duration_s"]:g} | {r["source"]["minimum_reported_support_margin_mm"]:.3f} | {r["interpolation"]["peak_interpolated_speed_degrees_s"]:.3f} | {r["interpolation"]["peak_interpolated_acceleration_degrees_s2"]:.3f} |')
lines += ['',f'Maximum evaluated joint-connection error: **{summary["maximum_evaluated_joint_connection_error_mm"]:.8f} mm**. Maximum foot-prediction error: **{summary["maximum_evaluated_foot_prediction_error_mm"]:.8f} mm**. Lowest sampled sole Z: **{summary["minimum_evaluated_sole_z_mm"]:.8f} mm**, a small interpolation/numerical residue.','', 'Every actuator source is continuous, bounded within its declared research envelope, and follows the measured four-bar branch. Every interpolation segment was checked at quarter points; peak speed and acceleration were calculated from the interpolant. Endpoint speeds are zero. These are demonstration demands, not loaded-servo capability measurements.','','The 2026-09-17 final comparison found later front-panel, camera and display changes relative to the preserved integration baseline; those current edits are retained. No leg meshes appear in the changed/missing list, and earlier actuator/body curves match all 19 recorded baseline frames. All twelve new actuator/body tracks also match every exported source sample (see `current-curve-source-review.json`). Body-contact points and complete-body floor results below describe the earlier measured geometry snapshot and have not been requalified for the later front changes. Completed preview frames span the saved model revisions; visor work remains deferred.','','Dead reaches its held semantic completion at **7.4 seconds**. Its full **12.3-second** demonstration includes optional standing recovery. The timing helper stops at semantic completion by default, and its explicit recovery flag enables the complete playlist path.','','Crab retains a **1.01 mm** minimum assumed margin and a documented **1.577 mm** final contact slide. Treat its support/friction assumptions as provisional. Other deliberate contact slides and body supports are documented per command.','','COM remains assumed. Actual servo travel calibration, loaded torque/current, brownouts, dynamics, contact load capacity and inter-part collisions remain unverified. Visor collision work is deferred at the owner’s request. A kinematic support margin does not establish physical stability.','','Before hardware execution: calibrate signed geometric joints to electrical centers/directions/endpoints; measure mass and payload positions; establish loaded speed/current limits and coordinated timing; verify real contact friction and body-contact strength. Firmware and Body Control code were not modified.']
(P/'validation-report.md').write_text('\n'.join(lines)+'\n')
print('Built reports for',len(reviews),'commands; Blender poses',summary['blender_poses_reviewed'])
